#!/bin/bash
# ACSGO - One-command VPS installation script
# Usage: curl -sSL https://raw.githubusercontent.com/DWISSNET/acslite/main/acsgo/deploy/install.sh | bash
# Or: bash install.sh

set -e

INSTALL_DIR="/opt/acsgo"
SERVICE_USER="acsgo"
BINARY_URL="https://github.com/DWISSNET/acslite/releases/latest/download/acsgo-linux-amd64"
REPO_URL="https://github.com/DWISSNET/acslite"
DATA_DIR="$INSTALL_DIR/data"
LOG_DIR="/var/log/acsgo"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_banner() {
  echo -e "${BLUE}"
  echo "  ___   ____ ____  ____  ___  "
  echo " / _ | / __// __/ / __ \/ _ \ "
  echo "/ __ |/ /__ \__ \/ /_/ / // / "
  echo "/_/ |_|\___/____/\____/\___/  "
  echo -e "${NC}"
  echo -e "${GREEN}ACSGO - Lightweight TR-069 ACS Server in Go${NC}"
  echo ""
}

check_root() {
  if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}❌ Please run as root (sudo bash install.sh)${NC}"
    exit 1
  fi
}

check_os() {
  if [ -f /etc/os-release ]; then
    . /etc/os-release
    echo -e "${GREEN}✅ OS: $NAME $VERSION_ID${NC}"
  else
    echo -e "${YELLOW}⚠️  Unknown OS - proceeding anyway${NC}"
  fi
}

install_dependencies() {
  echo -e "\n${BLUE}📦 Installing dependencies...${NC}"
  if command -v apt-get &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq curl wget gcc libc6-dev 2>/dev/null || true
  elif command -v yum &>/dev/null; then
    yum install -y -q curl wget gcc glibc-devel 2>/dev/null || true
  fi
  echo -e "${GREEN}✅ Dependencies ready${NC}"
}

install_go() {
  if command -v go &>/dev/null; then
    GO_VER=$(go version | awk '{print $3}')
    echo -e "${GREEN}✅ Go already installed: $GO_VER${NC}"
    return
  fi

  echo -e "\n${BLUE}📦 Installing Go 1.24...${NC}"
  GO_VERSION="1.24.0"
  GO_ARCH="amd64"
  GO_URL="https://dl.google.com/go/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz"

  wget -q "$GO_URL" -O /tmp/go.tar.gz
  tar -C /usr/local -xzf /tmp/go.tar.gz
  rm /tmp/go.tar.gz

  export PATH=$PATH:/usr/local/go/bin
  echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile.d/go.sh
  echo -e "${GREEN}✅ Go installed successfully${NC}"
}

create_user() {
  if ! id "$SERVICE_USER" &>/dev/null; then
    useradd --system --no-create-home --shell /bin/false "$SERVICE_USER"
    echo -e "${GREEN}✅ Created service user: $SERVICE_USER${NC}"
  fi
}

setup_directories() {
  echo -e "\n${BLUE}📁 Setting up directories...${NC}"
  mkdir -p "$INSTALL_DIR" "$DATA_DIR" "$LOG_DIR"
  chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR" "$LOG_DIR"
  echo -e "${GREEN}✅ Directories created${NC}"
}

build_binary() {
  echo -e "\n${BLUE}🔨 Building ACSGO binary...${NC}"

  BUILD_TMP=$(mktemp -d)
  cd "$BUILD_TMP"

  # Try to clone from repo
  if command -v git &>/dev/null; then
    git clone --depth 1 "$REPO_URL" repo 2>/dev/null || true
  fi

  if [ -d "$BUILD_TMP/repo/acsgo" ]; then
    cd "$BUILD_TMP/repo/acsgo"
    export PATH=$PATH:/usr/local/go/bin
    CGO_ENABLED=1 go build -ldflags="-s -w" -o "$INSTALL_DIR/acsgo" .
    echo -e "${GREEN}✅ Binary built from source${NC}"
  else
    echo -e "${YELLOW}⚠️  Could not clone repo, trying to download pre-built binary...${NC}"
    if wget -q "$BINARY_URL" -O "$INSTALL_DIR/acsgo" 2>/dev/null; then
      echo -e "${GREEN}✅ Binary downloaded${NC}"
    else
      echo -e "${RED}❌ Failed to get binary. Please build manually.${NC}"
      echo "   git clone $REPO_URL && cd acslite/acsgo && go build -o $INSTALL_DIR/acsgo ."
      exit 1
    fi
  fi

  chmod +x "$INSTALL_DIR/acsgo"
  chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/acsgo"
  rm -rf "$BUILD_TMP"
}

create_env_file() {
  if [ -f "$INSTALL_DIR/.env" ]; then
    echo -e "${YELLOW}⚠️  .env already exists, skipping${NC}"
    return
  fi

  # Generate random JWT secret
  JWT_SECRET=$(head -c 32 /dev/urandom | base64 | tr -d '=+/' | head -c 32)

  cat > "$INSTALL_DIR/.env" << EOF
# ACSGO Configuration
# Generated by install.sh on $(date)

ENV=production

# Server ports
CWMP_PORT=7547
PORT=7548

# Database (sqlite = embedded, postgres = external)
DB_TYPE=sqlite
DB_URL=$DATA_DIR/acsgo.db

# Authentication
JWT_SECRET=$JWT_SECRET
ADMIN_EMAIL=admin@acsgo.local
ADMIN_PASSWORD=admin123

# Uncomment for PostgreSQL:
# DB_TYPE=postgres
# DB_URL=******localhost:5432/acsgo?sslmode=disable
EOF

  chown "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR/.env"
  chmod 600 "$INSTALL_DIR/.env"
  echo -e "${GREEN}✅ Configuration file created: $INSTALL_DIR/.env${NC}"
}

install_systemd_service() {
  cat > /etc/systemd/system/acsgo.service << EOF
[Unit]
Description=ACSGO TR-069 ACS Server
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$INSTALL_DIR/.env
ExecStart=$INSTALL_DIR/acsgo
Restart=always
RestartSec=5
StandardOutput=append:$LOG_DIR/acsgo.log
StandardError=append:$LOG_DIR/acsgo-error.log

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$DATA_DIR $LOG_DIR

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable acsgo
  systemctl start acsgo
  echo -e "${GREEN}✅ Systemd service installed and started${NC}"
}

configure_firewall() {
  echo -e "\n${BLUE}🔥 Configuring firewall...${NC}"
  if command -v ufw &>/dev/null; then
    ufw allow 7547/tcp comment "ACSGO CWMP/TR-069" 2>/dev/null || true
    ufw allow 7548/tcp comment "ACSGO Web Dashboard" 2>/dev/null || true
    echo -e "${GREEN}✅ UFW rules added (7547, 7548)${NC}"
  elif command -v firewall-cmd &>/dev/null; then
    firewall-cmd --permanent --add-port=7547/tcp 2>/dev/null || true
    firewall-cmd --permanent --add-port=7548/tcp 2>/dev/null || true
    firewall-cmd --reload 2>/dev/null || true
    echo -e "${GREEN}✅ Firewalld rules added (7547, 7548)${NC}"
  else
    echo -e "${YELLOW}⚠️  No firewall detected - please manually open ports 7547 and 7548${NC}"
  fi
}

print_summary() {
  SERVER_IP=$(hostname -I | awk '{print $1}' 2>/dev/null || echo "YOUR_SERVER_IP")
  echo ""
  echo -e "${GREEN}╔═══════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║           ACSGO Installation Complete!            ║${NC}"
  echo -e "${GREEN}╚═══════════════════════════════════════════════════╝${NC}"
  echo ""
  echo -e "  ${BLUE}Dashboard:${NC}   http://$SERVER_IP:7548/dashboard"
  echo -e "  ${BLUE}CWMP Port:${NC}   $SERVER_IP:7547"
  echo -e "  ${BLUE}Login:${NC}       admin@acsgo.local / admin123"
  echo ""
  echo -e "  ${YELLOW}⚠️  Please change the default password in $INSTALL_DIR/.env${NC}"
  echo ""
  echo -e "  Useful commands:"
  echo -e "    systemctl status acsgo    - Check service status"
  echo -e "    systemctl restart acsgo   - Restart service"
  echo -e "    journalctl -u acsgo -f    - View live logs"
  echo -e "    cat $LOG_DIR/acsgo.log   - View log file"
  echo ""
  echo -e "  Config file: ${BLUE}$INSTALL_DIR/.env${NC}"
  echo ""
}

# Main
print_banner
check_root
check_os
install_dependencies
install_go
create_user
setup_directories
build_binary
create_env_file
install_systemd_service
configure_firewall
print_summary
